site_name: Dunda's Blog
site_description: A blog about SRE, DevOps, Platform Engineering, and more.
site_url: https://blog.dunda.me
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/code-tags
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/s33dunda
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/charles-dunda
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/s33dunda
  generator: false  # Removes the "Made with Material for MkDocs" text
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons/custom
          - material/icons/material/baseline
  - attr_list
  - md_in_html
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - overrides/partials/javascripts/extra.html
plugins:
  - search
  - tags
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      authors_file: .authors.yml
      authors: true
nav:
  - Home: index.md
