site_name: Dunda's Blog
site_description: A blog about SRE, DevOps, Platform Engineering, and more.
site_url: https://blog.dunda.me
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top        # Adds a "back to top" button
    - navigation.footer    # Adds footer navigation
    - search.suggest      # Adds search suggestions
    - search.highlight    # Highlights search results
    - content.code.copy   # Adds copy button to code blocks
    - content.code.annotate # Enables code annotations
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo     # Primary color for headers and links
      accent: deep purple # Accent color for buttons and interactive elements
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto         # Main text font
    code: Roboto Mono    # Code font
  icon:
    logo: material/code-tags  # Logo in the header
  favicon: assets/favicon.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons/custom    # Make sure this path is correct
          - material/icons/material/baseline
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - tags
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      authors_file: .authors.yml
      authors: true
nav:
  - Home: index.md
