authors:
  cdunda:
    name: Charles Dunda
    description: Platform Engineer
    avatar: https://github.com/s33dunda.png
    url: https://github.com/s33dunda
  s33d-innovations:
    name: S33D Innovations
    description: Platform Engineering Blog
    avatar: https://github.com/s33d-innovations.png
    url: https://s33d.io
